# Basic dependabot.yml file
# REF: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:
  # Enable version updates for Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Modify version updates on specified branch
    target-branch: "gh-pages"
    # Check for updates once a week
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Chore: "