#!/usr/bin/env pwsh

Write-Host "cardArchive index.md generator"

If (!(Test-Path -Path ./archiveRate.json)) {
    Write-Error -Message "archiveRate.json is required to generate the file" -ErrorId "archiveRate.jsonNotFound" -ErrorAction Stop
}

Write-Verbose "Loading json as hashtable"

$jsonIndex = (Get-Content -Path ./archiveRate.json -Raw | ConvertFrom-Json).data

Write-Verbose "Generating index.md"

$header = @"
<!-- markdownlint-disable MD036 MD033 -->

# Content Index

*This file is automatically generated from [archiveRate.json](./archiveRate.json) for database and [generateIndex.ps1](./generateIndex.md) using GitHub Actions*

***__Do not modify the file__***

## Table of Contents

<details>
<summary>Show Table of Content</summary>

"@

$header | Out-File -FilePath ./index.md -Encoding utf8

# Generate Table of Content

ForEach ($index in $jsonIndex) {
    "* [$($index.category)](#$($index.category))" | Out-File -FilePath ./index.md -Encoding utf8 -Append
}

"`n</details>" | Out-File -FilePath ./index.md -Encoding utf8 -Append

# Generate Content

ForEach ($index in $jsonIndex) {
    "`n## $($index.category)`n" | Out-File -FilePath ./index.md -Encoding utf8 -Append

    ForEach ($item in $index.editions) {
        $itemPath = "./$($index.category)/$($item.path)" 
        $itemEmoji = $item.emojiVisualIdentifier
        $itemSingular = $item.isNotSplit

        "* [$($itemEmoji) $($item.title) ``$($item.id)``]($($itemPath))" | Out-File -FilePath ./index.md -Encoding utf8 -Append

        If ($itemSingular) {
            "  Cards located on Edition folder, not on each staff. Below is the list of contributed staff:" | Out-File -FilePath ./index.md -Encoding utf8 -Append
        }

        ForEach ($staff in $item.contributors) {
            # Add reasons
            $status = $staff.status

            Switch ($status) {
                "invalid"  { $message = " &mdash; ⚠️ No cards from this staff were archived due to the link is invalid/missing" }
                "progress" { $message = " &mdash; 💳 Cards are being created by staff" }
                "halted"   { $message = " &mdash; 🚪 Staff left before finishing the requests" }
                "unknown"  { $message = " &mdash; ❓ Cards were not archived due to status is unknown" }
                Default    { $message = "" }
            }

            If (!($status -eq "archived")) {
                $staffPath = "$($staff.id)"
            } ElseIf ($itemSingular) {
                $staffPath = "$($staff.id)"
            } Else {
                $staffPath = "[$($staff.id)]($($itemPath)/$($staff.id))"
            }

            "  * $($staffPath)$($message)" | Out-File -FilePath ./index.md -Encoding utf8 -Append
        }
    }
}
