blank_issues_enabled: false
contact_links:
  - name: Contact The Newbie Club's GFX-CD Administrator
    url: https://myanimelist.net/mymessages.php?go=send&toname=nattadasu
    about: Ask @nattadasu via MyAnimeList PM anything related on this repo.
  - name: Contact The Newbie Club's GFX-CD Deputy
    url: https://myanimelist.net/mymessages.php?go=send&toname=Annie_Law
    about: Ask @Annie_Law via MyAnimeList PM anything related on this repo.
  - name: Contact The Newbie Club's Owner
    url: https://myanimelist.net/mymessages.php?go=send&toname=Karasian
    about: Ask @Karasian via MyAnimeList PM anything related on this repo.