name: Report a Problem/Ask a Question
description: "Choose this if you encounter any problem with the card dump. Including, but not limited to: missing cards, corrupted files, etc."
assignees:
  - nattadasu
labels:
  - question
title: "[Question-Report]: "
body:
  - type: markdown
    attributes:
      value: |
        If you have any questions about this issue template, contact:
        * [nattadasu](https://myanimelist.net/mymessages.php?go=send&toname=nattadasu) as GFX Admin,
        * [Annie_Law](https://myanimelist.net/mymessages.php?go=send&toname=Annie_Law) as GFX Deputy, or
        * [Karasian](https://myanimelist.net/mymessages.php?go=send&toname=Karasian) as club owner.
  - type: input
    id: username
    attributes:
      label: Your MAL Username
      placeholder: un1corn_tnc
    validations:
      required: true
  - type: input
    id: year
    attributes:
      label: Year
      description: Which year the edition released? Leave if you want to ask general question.
      placeholder: "2022"
    validations:
      required: false
  - type: input
    id: entryId
    attributes:
      label: Entry/Complaint ID
      description: Entry ID on card delivery tracking forum thread or Complaint ID attached on card deliverer's message. Leave if you want to ask general question.
      placeholder: 22MARA6THUN1059
    validations:
      required: false
  - type: input
    id: editionTopic
    attributes:
      label: Edition Topic
      description: What edition you provided for missing files? Leave if you want to ask general question.
      placeholder: 6th Anniversary
    validations:
      required: false
  - type: input
    id: staff
    attributes:
      label: Staff in Charge
      description: Who owns the card designs? Leave if you want to ask general question.
      placeholder: nattadasu
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Please describe the problem you encountered."
      placeholder: |
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Gravida neque convallis a cras semper. Ultrices vitae auctor eu augue ut lectus. Congue nisi vitae suscipit tellus mauris a. Et leo duis ut diam quam nulla porttitor. Malesuada pellentesque elit eget gravida cum sociis natoque. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Facilisis gravida neque convallis a. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Dignissim diam quis enim lobortis. Congue eu consequat ac felis donec et odio.

        Sagittis eu volutpat odio facilisis mauris sit amet massa. Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus. Pellentesque habitant morbi tristique senectus. Elementum curabitur vitae nunc sed velit dignissim sodales. Hendrerit dolor magna eget est lorem ipsum dolor sit. Maecenas sed enim ut sem viverra aliquet eget sit. Dui accumsan sit amet nulla facilisi. Venenatis cras sed felis eget. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Donec ultrices tincidunt arcu non sodales neque sodales. Cras tincidunt lobortis feugiat vivamus. Faucibus turpis in eu mi bibendum neque. Volutpat ac tincidunt vitae semper quis. Egestas purus viverra accumsan in nisl nisi scelerisque.
    validations:
      required: true
