name: Replace variables to string
on:
  push:
  workflow_dispatch:

jobs:
  cancel:
    name: 'Cancel GitHub Pages build'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: 23230381
          access_token: ${{ github.token }}

  stringReplace:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
          ref: gh-pages

      - name: Find and Replace Committer
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{committer}}"
          replace: "${{ github.actor }}"
          regex: false
          include: "index.html"

      - name: Find and Replace Repository
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{author}}"
          replace: "${{ github.repository_owner }}"
          regex: false
          include: "index.html"

      - name: Find and Replace Repository
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{repo}}"
          replace: "${{ github.repository }}"
          regex: false
          include: "index.html"

      - name: Commit sources
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "Variable replace"
          commit_options: --allow-empty
          file_pattern: .
          branch: gh-pages