name: Replace variables to string
on:
  push:
  workflow_dispatch:

jobs:
  stringReplace:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
          ref: gh-pages

      - name: Find and Replace Committer
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{committer}}"
          replace: "${{ github.actor }}"
          regex: false
          include: "index.html"

      - name: Find and Replace Repository
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{author}}"
          replace: "${{ github.repository_owner }}"
          regex: false
          include: "index.html"

      - name: Find and Replace Repository
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{repo}}"
          replace: "${{ github.repository }}"
          regex: false
          include: "index.html"

      - name: Commit sources
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: "String replace: Windows absolute path to GitHub RAW Links"
          commit_options: --allow-empty
          file_pattern: .
          branch: gh-pages