# cSpell:words pwsh

name: Auto Update index and statistic

on:
  push:
    paths:
      - "./generateIndex.ps1"
      - "archiveRate.json"
      - "./generateStatistic.ps1"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate files
        shell: pwsh
        run: |
          ./generateIndex.ps1
          ./generateStatistic.ps1
      - name: Commit changes
        shell: pwsh
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add index.md
          git commit -m "Update generated document"

          git push
